### PR TITLE
Use AdvancedExternalizers to not need wrapping objects in adapters

### PR DESCRIPTION
**Pull request by Sanne**
Hi @tsegismont , you don't need to pre-process each Key and Value using the DataConverter if you pre-register the externalizers and provide a type/externalizer map.

Made an example in this PR - I think this works but I couldn't test it as it seems the tesuite you have isn't actually ever serializing these objects (!?).

### CODE REVIEW

**Comment by tsegismont** [comment]
Hi @Sanne , I had looked at AdvancedExternalizers during prototyping. The issue is that ClusterSerializable is an interface and, IIUC, it won't work "currently the framework only supports class equality comparison and so, it’s not possible to indicate that the classes to marshalled are all children of a particular class/interface"
http://infinispan.org/docs/stable/user_guide/user_guide.html#advanced_externalizers

So as I had to do it like this for ClusterSerializable, I went the same way with ServerID.

**Comment by Sanne** [comment]
ok I missed that detail for `ClusterSerializable`.
I'd suggest to follow this approach for the other types though to not allocate those wrapper objects.

Also, sooner or later you're going to need an `InfinispanModuleInitializer`: it's a nice way to add additional features. For example I suspect you could benefit from implementing custom `Command` s

**Comment by Sanne** [comment]
BTW I'll close this as it was mostly meant to show the alternative approach. Too bad that you need to invoke this `DataConverter` explicitly.. one alternative would be to inject a custom Marshaller, but that's probably overkill if the codebase doesn't get much more complex.

**Comment by tsegismont** [comment]
Do you know if it would be difficult to create a custom marshaller who
takes care of ServerID, multimapkey and objects implements
ClusterSerializable, but would fallback to JBossMarshaller otherwise?

2016-09-02 16:12 GMT+02:00 Sanne Grinovero <notifications@github.com>:

**Pull request closed without merging**
